default_stages:
  - commit
fail_fast: false
minimum_pre_commit_version: "2.17.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: validate-commit-msg
        name: Validate Commit Message
        language: system
        entry: python local_pre_commit_hooks/validate_commit_message.py
        args: [.git/COMMIT_EDITMSG]
        stages:
          - commit-msg
        always_run: true
        verbose: true

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ["--ignore=E501,F401,E902"] # Properly configured ignore argument

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
